Arch uses dbus:dbus instead of messagebus:messagebus.

diff --git a/host-bin/enter-chroot b/host-bin/enter-chroot
--- a/host-bin/enter-chroot
+++ b/host-bin/enter-chroot
@@ -648,7 +648,7 @@ ret=0
 if [ "$NOLOGIN" != 1 ] && grep -q '^root:' "$passwd" 2>/dev/null; then
     # Try to detect the dbus user by parsing its configuration file
     # If it fails, or if the user does not exist, `id -un '$dbususer'`
-    # will fail, and we fallback on a default user name ("messagebus")
+    # will fail, and we fallback on a default user name ("dbus")
     dbususer="`echo "cat /busconfig/user/text()" \
         | xmllint --shell "$CHROOT/etc/dbus-1/system.conf" 2>/dev/null \
         | grep '^[a-z][-a-z0-9_]*$' || true`"
@@ -666,8 +666,8 @@ if [ "$NOLOGIN" != 1 ] && grep -q '^root:' "$passwd" 2>/dev/null; then
             rm -f "$pidfile"
         fi
         mkdir -p /var/run/dbus
-        dbususer="`id -un "$dbususer" 2>/dev/null || echo "messagebus"`"
-        dbusgrp="`id -gn "$dbususer" 2>/dev/null || echo "messagebus"`"
+        dbususer="`id -un "$dbususer" 2>/dev/null || echo "dbus"`"
+        dbusgrp="`id -gn "$dbususer" 2>/dev/null || echo "dbus"`"
         chown "$dbususer:$dbusgrp" /var/run/dbus
         exec dbus-daemon --system --fork' || ret=$?
     if [ "$ret" != 0 ]; then
